insert into public.products (
  name,
  slug,
  description,
  price,
  compare_price,
  stock,
  main_category,
  sub_category,
  image_url,
  gallery_urls,
  sizes,
  is_out_of_stock,
  is_new,
  is_best_seller
)
values
  (
    'Aura',
    'aura',
    'Robe féminine fluide, coupe élégante et tombé léger pour un look premium.',
    25000,
    32000,
    20,
    'Vêtements Femmes',
    'Robes',
    '/products/aura-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    true,
    true
  ),
  (
    'Body Shaping Jumpsuit',
    'body-shaping-jumpsuit',
    'Body sculptant effet gainant, maintien confortable et coupe seconde peau.',
    25000,
    null,
    18,
    'Sous-vêtements & Pyjamas',
    'Lingerie',
    '/products/body-shaping-jumpsuit-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    true,
    false
  ),
  (
    'Cape Celeste',
    'cape-celeste',
    'Cape élégante aux lignes épurées, parfaite pour une allure chic.',
    28000,
    34000,
    16,
    'Vêtements Femmes',
    'Robes',
    '/products/cape-celeste-01.webp',
    array['/products/cape-celeste-02.webp', '/products/cape-celeste-03.webp'],
    array['S', 'M', 'L', 'XL'],
    false,
    true,
    true
  ),
  (
    'Causal Pant Suit',
    'causal-pant-suit',
    'Ensemble tailoring casual, raffiné et facile à porter.',
    30000,
    null,
    14,
    'Vêtements Femmes',
    'Tenues de sport',
    '/products/causal-pant-suit-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    false,
    false
  ),
  (
    'Chrysalide Nocturne',
    'chrysalide-nocturne',
    'Robe sophistiquée aux reflets profonds, parfaite pour vos soirées.',
    35000,
    42000,
    12,
    'Vêtements Femmes',
    'Robes',
    '/products/chrysalide-nocturne-01.webp',
    array['/products/chrysalide-nocturne-02.webp', '/products/chrysalide-nocturne-03.webp'],
    array['S', 'M', 'L', 'XL'],
    false,
    true,
    true
  ),
  (
    'Combinaison de sport imprimé Leopard',
    'combinaison-de-sport-imprime-leopard',
    'Combinaison sport ultra stretch, imprimé tendance et confort total.',
    22000,
    null,
    24,
    'Vêtements Femmes',
    'Tenues de sport',
    '/products/combinaison-de-sport-imprime-leopard-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    true,
    false
  ),
  (
    'Jean Déchiré Mi-Taille Pliée',
    'jean-dechire-mi-taille-pliee',
    'Jean denim tendance avec coupe moderne et détails déchirés.',
    24000,
    null,
    20,
    'Vêtements Femmes',
    'Pantalons',
    '/products/jean-dechire-mi-taille-pliee-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    false,
    false
  ),
  (
    'Jogging Set',
    'jogging-set',
    'Ensemble jogging doux, coupe confort et style urbain.',
    26000,
    32000,
    18,
    'Vêtements Femmes',
    'Tenues de sport',
    '/products/jogging-set-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    false,
    true
  ),
  (
    'Lumière d''Aube',
    'lumiere-d-aube',
    'Robe légère et lumineuse, parfaite pour une allure douce.',
    27000,
    null,
    16,
    'Vêtements Femmes',
    'Robes',
    '/products/lumiere-d-aube-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    true,
    false
  ),
  (
    'Midnight Elegance',
    'midnight-elegance',
    'Ensemble top et pantalon ajusté pour un look evening moderne.',
    36000,
    null,
    10,
    'Vêtements Femmes',
    'Pantalons',
    '/products/midnight-elegance-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    true,
    true
  ),
  (
    'Midnight Muse',
    'midnight-muse',
    'Pièce statement au tombé fluide, look premium assuré.',
    34000,
    40000,
    12,
    'Vêtements Femmes',
    'Robes',
    '/products/midnight-muse-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    true,
    true
  ),
  (
    'Mint Cascade',
    'mint-cascade',
    'Combinaison pantalon pastel, coupe ajustée et allure chic.',
    23000,
    null,
    22,
    'Vêtements Femmes',
    'Pantalons',
    '/products/mint-cascade-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    false,
    false
  ),
  (
    'Pink Flower',
    'pink-flower',
    'Ensemble veste denim et jean coordonne pour un style casual premium.',
    25000,
    null,
    20,
    'Vêtements Femmes',
    'Vestes',
    '/products/pink-flower-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    false,
    false
  ),
  (
    'Skye',
    'skye',
    'Ensemble près du corps, confortable et adapté au style athleisure.',
    26000,
    null,
    18,
    'Vêtements Femmes',
    'Tenues de sport',
    '/products/skye-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    false,
    false
  ),
  (
    'Urban Wanderer',
    'urban-wanderer',
    'Combinaison pantalon élégante pour un style urbain affirmé.',
    24000,
    null,
    24,
    'Vêtements Femmes',
    'Pantalons',
    '/products/urban-wanderer-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    false,
    false
  ),
  (
    'Yoga Flow Short à manches courtes',
    'yoga-flow-short-a-manches-courtes',
    'Ensemble sport doux, respirant et parfaitement ajusté.',
    22000,
    28000,
    26,
    'Vêtements Femmes',
    'Tenues de sport',
    '/products/yoga-flow-short-a-manches-courtes-01.webp',
    array['/products/yoga-flow-short-a-manches-courtes-02.webp', '/products/yoga-flow-short-a-manches-courtes-03.webp', '/products/yoga-flow-short-a-manches-courtes-04.webp', '/products/yoga-flow-short-a-manches-courtes-05.webp', '/products/yoga-flow-short-a-manches-courtes-06.webp', '/products/yoga-flow-short-a-manches-courtes-07.webp', '/products/yoga-flow-short-a-manches-courtes-08.webp', '/products/yoga-flow-short-a-manches-courtes-09.webp', '/products/yoga-flow-short-a-manches-courtes-10.webp'],
    array['S', 'M', 'L', 'XL'],
    false,
    true,
    true
  ),
  (
    'Yoga Set',
    'yoga-set',
    'Ensemble yoga confort, maintien et style premium.',
    21000,
    null,
    30,
    'Vêtements Femmes',
    'Tenues de sport',
    '/products/yoga-set-01.webp',
    array[]::text[],
    array['S', 'M', 'L', 'XL'],
    false,
    true,
    false
  )
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  compare_price = excluded.compare_price,
  stock = excluded.stock,
  main_category = excluded.main_category,
  sub_category = excluded.sub_category,
  image_url = excluded.image_url,
  gallery_urls = excluded.gallery_urls,
  sizes = excluded.sizes,
  is_out_of_stock = excluded.is_out_of_stock,
  is_new = excluded.is_new,
  is_best_seller = excluded.is_best_seller,
  updated_at = now();
